In [39]:
import torch


In [40]:
x = torch.empty(5, 3)
print(x)


tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [41]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5220, 0.8402, 0.2552],
        [0.5674, 0.2499, 0.7551],
        [0.9218, 0.5982, 0.8381],
        [0.5930, 0.5254, 0.6371],
        [0.8515, 0.9360, 0.1212]])


In [42]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [43]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [44]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7848, -1.1250,  0.0551],
        [-1.1581,  0.0728,  1.4652],
        [ 0.1579, -0.9810, -1.1899],
        [-0.4872,  0.0762, -0.5793],
        [ 2.0287,  0.9516,  0.5986]])


In [45]:
print(x.size())

torch.Size([5, 3])


In [46]:
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)


tensor([[-0.4205, -1.0782,  0.0660],
        [-0.8192,  1.0518,  1.5074],
        [ 0.5336, -0.4153, -0.3457],
        [ 0.2781,  1.0653,  0.2250],
        [ 2.2360,  1.3631,  1.4292]])
tensor([[-0.4205, -1.0782,  0.0660],
        [-0.8192,  1.0518,  1.5074],
        [ 0.5336, -0.4153, -0.3457],
        [ 0.2781,  1.0653,  0.2250],
        [ 2.2360,  1.3631,  1.4292]])
tensor([[-0.4205, -1.0782,  0.0660],
        [-0.8192,  1.0518,  1.5074],
        [ 0.5336, -0.4153, -0.3457],
        [ 0.2781,  1.0653,  0.2250],
        [ 2.2360,  1.3631,  1.4292]])


In [47]:
#Add in-place
y.add_(x)
print(y)



tensor([[-0.4205, -1.0782,  0.0660],
        [-0.8192,  1.0518,  1.5074],
        [ 0.5336, -0.4153, -0.3457],
        [ 0.2781,  1.0653,  0.2250],
        [ 2.2360,  1.3631,  1.4292]])


In [48]:
#Numpy Operation demo
print(x)
print(x[:, 1])


tensor([[-0.7848, -1.1250,  0.0551],
        [-1.1581,  0.0728,  1.4652],
        [ 0.1579, -0.9810, -1.1899],
        [-0.4872,  0.0762, -0.5793],
        [ 2.0287,  0.9516,  0.5986]])
tensor([-1.1250,  0.0728, -0.9810,  0.0762,  0.9516])


In [49]:
# Resizing Demo
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [50]:
#Convert to python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4685])
1.4684773683547974


In [51]:
### Converting to and from NumPy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

### The numpy value is based on the torch value
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [52]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [53]:
if torch.cuda.is_available():
	device = torch.device("cuda")
	y = torch.ones_like(x, device=device)
	x = x.to(device)
	z = x + y
	print(z)
	print(z.to('cpu', torch.double))