In [38]:
"""
IMPORTS
"""
import torch
import numpy as np

In [39]:
"""
FUNCTIONS
"""

# Prints summary of a tensor
def describe(x: torch.Tensor):
	print(f'Type: {x.type()}')
	print(f'Shape/size: {x.shape}')
	print(f'Values: \n{x}\n')

In [40]:
describe(torch.Tensor(2,3))
describe(torch.rand(2,3)) #Random
describe(torch.randn(2,3)) #Normal Random

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.3090e+22, 1.0357e-11, 6.4829e-10],
        [5.4170e-05, 2.1234e+20, 1.6517e-04]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.8000, 0.5738, 0.6727],
        [0.4992, 0.2968, 0.6410]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.3597, -0.0364, -1.1886],
        [-1.3518,  0.2334, -0.0256]])



In [41]:
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])



In [42]:
x = torch.Tensor([[1,2,3],
			 [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [43]:
# Coming from Numpy
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))


Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.0738, 0.9093, 0.7388],
        [0.3494, 0.7278, 0.4802]], dtype=torch.float64)



In [44]:
# Tensor Types
x = torch.FloatTensor([[1,2,3],
					   [4,5,6]])
describe(x)

x = x.long()
describe(x)

x = torch.tensor([[1,2,3],
				  [4,5,6]],
				 dtype=torch.int64)
describe(x)

x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [45]:
"""
Tensor Operations
"""

x = torch.randn(2,3)
describe(x)
describe(torch.add(x, x))
describe(x+x)


Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.2037, -0.3496, -0.5870],
        [-0.0744, -0.5539,  0.8527]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4074, -0.6992, -1.1739],
        [-0.1487, -1.1078,  1.7054]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4074, -0.6992, -1.1739],
        [-0.1487, -1.1078,  1.7054]])



In [46]:
"""
Dimension operations
"""

x = torch.arange(6)
describe(x)

x = x.view(2,3)
describe(x)

describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))
describe(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])



In [47]:
"""
Slicing and indexing
"""

x = torch.arange(6).view(2, 3)
describe(x)

describe(x[:2, :1])

describe(x[0, 1])


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 1])
Values: 
tensor([[0],
        [3]])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1



In [48]:
describe(x)
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

row_indicies = torch.arange(2).long()
col_indicies = torch.LongTensor([0, 1])
describe(x[row_indicies, col_indicies])


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])



In [49]:
x = torch.arange(6).view(2,3)
describe(x)

describe(torch.cat([x, x], dim=0))

describe(torch.stack([x, x]))


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



In [50]:
x1 = torch.arange(6).view(2, 3).float()
describe(x1)

x2 = torch.ones(3,2)
x2[:, 1] += 1
describe(x2)


describe(torch.mm(x1, x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])



In [51]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

True


In [52]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

True


In [53]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0

False
